networks:
  bgp-test:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.0.2.0/24
          gateway: 192.0.2.1

services:
  # exabgp_announcer:
  #   container_name: exabgp_announcer
  #   image: franciscobonand04/exabgp:0.0.0
  #   volumes:
  #     - $PWD/bgp-announcer/confs:/etc/exabgp:rw
  #     - $PWD/bgp-announcer/scripts:/opt/bgp-announcer/scripts:rw
  #   networks:
  #     bgp-test:
  #       ipv4_address: 192.0.2.2

  frr:
    container_name: frr_router
    privileged: false
    cap_add: # Linux kernel capabilities needed for setup
      - CAP_NET_ADMIN
      - CAP_NET_RAW
      - CAP_SYS_ADMIN
    image: quay.io/frrouting/frr:8.5.1
    volumes:
      - $PWD/routers/frr/confs:/etc/frr:rw
    networks:
      bgp-test:
        ipv4_address: 192.0.2.3

  bird:
    container_name: bird_router
    privileged: false
    cap_add: # Linux kernel capabilities needed for setup
      - CAP_NET_ADMIN
      - CAP_NET_RAW
      - CAP_SYS_ADMIN
    image: franciscobonand04/bird:0.0.0
    volumes:
      - $PWD/routers/bird/confs:/etc/bird:rw
    networks:
      bgp-test:
        ipv4_address: 192.0.2.4
  #
  #
  #  exabgp_listener:
  #    container_name: exabgp_listener
  #    image: pierky/exabgp:4.2.11
  #    volumes:
  #      - $PWD/bgp-listener/confs:/etc/exabgp:rw

  exabgp_listener:
    container_name: exabgp_listener
    image: franciscobonand04/exabgp:0.0.0
    volumes:
      - $PWD/bgp-listener/confs:/etc/exabgp:rw
      - $PWD/bgp-listener/scripts:/opt/bgp-listener/scripts:rw
    networks:
      bgp-test:
        ipv4_address: 192.0.2.5
